### ISSUE TITLE
Loading Pre trained Weights into the Generator

### ISSUE THREAD

**Issue by jetlime** [imatge-upc/pathgan#11]
With both Tensorflow, 1.14.0 and 2.X, and Python 2.7, 

I get a Value error when loading the pretrained weights into the generator.
ValueError: You are trying to load a weight file containing 22 layers into a model with 10 layers.

**Comment by matteochestnut** [comment]
I'm much late on this but it can be helpful in the future; a solution could be using those weights linked in the readme from an older commit:
https://drive.google.com/open?id=1p3Wn3C9doWiX4DqyDFQeMvCBwGZHHECo
Those weights are compatible with the architecture of the model provided in the repository.

This is the commit I'm referring to:
https://github.com/imatge-upc/pathgan/commit/cb7187ee22dfdc2d1fd8b11335d2345d9f14fbf6
Those are the last weights published before the current ones.
